// registry.hpp — suite definitions and factory wirings
#pragma once

#include <map>
#include <string>
#include <vector>

#include "inop.hpp"

namespace inop {

struct Suite {
    std::string code;         // "26" | "38"
    std::string name;         // display name
    std::string alphabet;     // symbol set
    int min_rotors;           // rotors used per message — inclusive range
    int max_rotors;           // (Legacy is fixed: min == max == 3)
    int max_plug_pairs;
    int max_notches;
    std::vector<std::string> rotor_names;
    std::vector<std::string> reflector_names;
    bool notches_are_fixed;   // legacy wheels ship with historic notches
    bool historic_lock;       // true = a faithful period machine, no INOP features
    int  block;               // transmission group width
};

const std::map<std::string, Suite>& suites();
const Suite& suite(const std::string& code);

// Fresh, independent wheel instances for the given suite.
Rotor make_rotor(const std::string& name, const Alphabet& alpha);
Reflector make_reflector(const std::string& name, const Alphabet& alpha);

// A wiring that is a pure rotation (Caesar shift) of `alphabet`, ranked by
// each symbol's position in `alphabet` itself — NOT by std::sort/ASCII
// order. Those two orderings coincide for ALPHA26 (A-Z is already
// ASCII-sorted) but diverge for ALPHA38, where digits, '#' and '/' sort
// before letters in ASCII yet come after them in the declared alphabet.
// Ranking by ASCII would let a genuine shift cipher of ALPHA38 through.
// `wiring` is assumed to already be a permutation of `alphabet`.
bool wiring_is_rotation(const std::string& wiring, const std::string& alphabet);

// ── runtime wheel loading ───────────────────────────────────────────────
//
// Wheels generated by the maintenance menu live in a plain text file:
//   rotor     <name> <wiring> [notches]
//   reflector <name> <wiring>
// A wheel belongs to whichever suite its wiring length matches. Loaded
// wheels sit alongside the built-ins and shadow them on a name clash.
// The pool is VALIDATED on load. A wheel file is rejected outright — nothing
// from it is loaded — if it contains duplicate wirings or a wiring that is a
// pure rotation of the alphabet, because both are what a broken generator
// produces and neither is ever legitimate. Problems are appended to
// *problems if given.
// Returns the number of wheels loaded; 0 if the file is absent or rejected.
int load_wheel_file(const std::string& path, std::vector<std::string>* problems = 0);

// Every wheel usable with this suite — built in and loaded — sorted.
std::vector<std::string> available_rotors(const Suite& s);
std::vector<std::string> available_reflectors(const Suite& s);

bool rotor_exists(const std::string& name, const Suite& s);
bool reflector_exists(const std::string& name, const Suite& s);

}  // namespace inop
