// registry.hpp — suite definitions and factory wirings
#pragma once

#include <map>
#include <string>
#include <vector>

#include "inop.hpp"

namespace inop {

struct Suite {
    std::string code;         // "26" | "38"
    std::string name;         // display name
    std::string alphabet;     // symbol set
    int min_rotors;           // rotors used per message — inclusive range
    int max_rotors;           // (Legacy is fixed: min == max == 3)
    int max_plug_pairs;
    int max_notches;
    std::vector<std::string> rotor_names;
    std::vector<std::string> reflector_names;
    bool notches_are_fixed;   // legacy wheels ship with historic notches
    bool historic_lock;       // true = a faithful period machine, no INOP features
    int  block;               // transmission group width
};

const std::map<std::string, Suite>& suites();
const Suite& suite(const std::string& code);

// Fresh, independent wheel instances for the given suite.
Rotor make_rotor(const std::string& name, const Alphabet& alpha);
Reflector make_reflector(const std::string& name, const Alphabet& alpha);

// A wiring that is a pure rotation (Caesar shift) of `alphabet`, ranked by
// each symbol's position in `alphabet` itself — NOT by std::sort/ASCII
// order. Those two orderings coincide for ALPHA26 (A-Z is already
// ASCII-sorted) but diverge for ALPHA38, where digits, '#' and '/' sort
// before letters in ASCII yet come after them in the declared alphabet.
// Ranking by ASCII would let a genuine shift cipher of ALPHA38 through.
// `wiring` is assumed to already be a permutation of `alphabet`.
bool wiring_is_rotation(const std::string& wiring, const std::string& alphabet);

// The largest max_notches of any suite. A compile-time constant because an
// interface needs a fixed bound for its notch fields, and the self-test
// checks it against the suite table so the two cannot drift apart. They
// already did once: the GUI carried three notch boxes because max_notches
// was 3 when it was written, and went on carrying three after the cap
// moved to 5, silently truncating a generated 5-notch rotor to its first
// three.
constexpr int kMaxNotchesAnySuite = 5;

// A notch symbol may appear at most once across a whole machine, not
// merely once per rotor. Returns every symbol that appears more than once
// across `notches_per_rotor`, in first-seen order, or an empty string if
// they are all distinct. Every offender rather than the first, so an
// interface can mark all the rows involved in one pass instead of
// surfacing a second clash only after the operator has fixed the first.
//
// This is the rule the generator enforces structurally, by drawing every
// notch from one shuffled pool, and it belongs in one place: the same
// lesson the rotation check already learned, where the generator and the
// loader each had their own copy until they disagreed. The GUI enforced it
// independently in the interface layer until this function existed.
//
// Note on the justification, which is disputed. The stated reason has been
// that two rotors sharing a notch shrinks the keyspace, and the arithmetic
// says the opposite: independent draws give C(38,3)^10 which is about
// 10^39.3, while the disjoint pool gives 38!/(3!^10 * 8!), about 10^32.3.
// Disjointness costs roughly seven orders of magnitude. Whether the rule
// should survive that is register item 34 and is not decided here. What is
// decided here is that while it stands, it stands in exactly one place.
std::string duplicate_notch_symbols(const std::vector<std::string>& notches_per_rotor);

// ── runtime wheel loading ───────────────────────────────────────────────
//
// Wheels generated by the maintenance menu live in a plain text file:
//   rotor     <name> <wiring> [notches]
//   reflector <name> <wiring>
// A wheel belongs to whichever suite its wiring length matches. Loaded
// wheels sit alongside the built-ins and shadow them on a name clash.
// The pool is VALIDATED on load. A wheel file is rejected outright — nothing
// from it is loaded — if it contains duplicate wirings or a wiring that is a
// pure rotation of the alphabet, because both are what a broken generator
// produces and neither is ever legitimate. Problems are appended to
// *problems if given.
// Returns the number of wheels loaded; 0 if the file is absent or rejected.
//
// The file is JSON as of 2.3.0: an object with optional "rotors" and
// "reflectors" arrays of {name, wiring, notches}. Both keys being optional
// is what lets the two default files below and a single combined file all
// go through this one reader.
int load_wheel_file(const std::string& path, std::vector<std::string>* problems = 0);

bool validate_wheel_file(const std::string& path, std::vector<std::string>* problems = 0);

bool validate_wheel_document(const std::string& json,
                             std::vector<std::string>* problems = 0);

// The two files loaded automatically at startup. Rotors and reflectors are
// kept apart so a bad reflector cannot cost you every rotor: a wheel file
// is rejected whole, and splitting them halves what one bad entry takes
// down with it.
extern const char* const kRotorsPath;      // inop_rotors.json
extern const char* const kReflectorsPath;  // inop_reflectors.json

// One-time conversion of a 2.2.x plain-text wheel file into the two JSON
// files. Does nothing and returns 0 if the text file is absent, or if
// either target already exists — replacing current key material with the
// contents of a stale text file is the worst outcome available, so the
// safe answer to any ambiguity is to leave everything alone. The original
// is never deleted. Returns the number of wheels converted.
int migrate_wheels_from_text(const std::string& txt_path, const std::string& rotors_path,
                             const std::string& reflectors_path,
                             std::vector<std::string>* problems = 0);

// Every wheel usable with this suite — built in and loaded — sorted.
std::vector<std::string> available_rotors(const Suite& s);
std::vector<std::string> available_reflectors(const Suite& s);

}  // namespace inop
